package view;

import java.awt.Dimension;
import java.awt.Graphics;

/**
 * @author LeonardoSotillo
 * @author FernandoRainier
 * version 1.0.0
 */
public class AddProductWindow extends VentaOnline {
    
    /**
     * Creates new form AddProductWindow
     */
    public AddProductWindow() {
        initComponents();
        image.cargarImg();
    }
    
        MostrarImage image = new MostrarImage();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPAddProductWindow = new javax.swing.JPanel();
        jLTittleAddProduct = new javax.swing.JLabel();
        jLNameProduct = new javax.swing.JLabel();
        jLCategoryProduct = new javax.swing.JLabel();
        jLPrice = new javax.swing.JLabel();
        jLProvider = new javax.swing.JLabel();
        jLQuantity = new javax.swing.JLabel();
        jLImage = new javax.swing.JLabel();
        jTFNameProduct = new javax.swing.JTextField();
        jTFPrice = new javax.swing.JTextField();
        jTFProvider = new javax.swing.JTextField();
        jTFQuantity = new javax.swing.JTextField();
        jBAddProduct = new javax.swing.JButton();
        jBCancel = new javax.swing.JButton();
        jBAddImage = new javax.swing.JButton();
        jLImagen = new javax.swing.JLabel();
        jCBCategory = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPAddProductWindow.setBackground(new java.awt.Color(255, 255, 255));

        jLTittleAddProduct.setBackground(new java.awt.Color(255, 255, 255));
        jLTittleAddProduct.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLTittleAddProduct.setForeground(new java.awt.Color(0, 0, 255));
        jLTittleAddProduct.setText("AGREGAR PRODUCTO");

        jLNameProduct.setBackground(new java.awt.Color(255, 255, 255));
        jLNameProduct.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLNameProduct.setText("Nombre");

        jLCategoryProduct.setBackground(new java.awt.Color(255, 255, 255));
        jLCategoryProduct.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLCategoryProduct.setText("Categoria");

        jLPrice.setBackground(new java.awt.Color(255, 255, 255));
        jLPrice.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLPrice.setText("Precio");

        jLProvider.setBackground(new java.awt.Color(255, 255, 255));
        jLProvider.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLProvider.setText("Proveedor de origen");

        jLQuantity.setBackground(new java.awt.Color(255, 255, 255));
        jLQuantity.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLQuantity.setText("Cantidad minima en existencia");

        jLImage.setBackground(new java.awt.Color(255, 255, 255));
        jLImage.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLImage.setText("Imagen del producto");

        jTFNameProduct.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jTFPrice.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTFPrice.setToolTipText("");

        jTFProvider.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jTFQuantity.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jBAddProduct.setBackground(new java.awt.Color(255, 255, 255));
        jBAddProduct.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jBAddProduct.setText("AGREGAR");

        jBCancel.setBackground(new java.awt.Color(255, 255, 255));
        jBCancel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jBCancel.setText("CANCELAR");
        jBCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelActionPerformed(evt);
            }
        });

        jBAddImage.setBackground(new java.awt.Color(255, 255, 255));
        jBAddImage.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jBAddImage.setText("AGREGAR IMAGEN");

        jLImagen.setBackground(new java.awt.Color(255, 255, 255));

        jCBCategory.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "zapatos", "celulares", "tecnologia", "libros", "ropa" }));

        javax.swing.GroupLayout jPAddProductWindowLayout = new javax.swing.GroupLayout(jPAddProductWindow);
        jPAddProductWindow.setLayout(jPAddProductWindowLayout);
        jPAddProductWindowLayout.setHorizontalGroup(
            jPAddProductWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPAddProductWindowLayout.createSequentialGroup()
                .addGroup(jPAddProductWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPAddProductWindowLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLTittleAddProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPAddProductWindowLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPAddProductWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBAddImage)
                            .addGroup(jPAddProductWindowLayout.createSequentialGroup()
                                .addGroup(jPAddProductWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLImage)
                                    .addComponent(jLQuantity)
                                    .addComponent(jLProvider)
                                    .addComponent(jLPrice)
                                    .addComponent(jLCategoryProduct)
                                    .addComponent(jLNameProduct))
                                .addGap(18, 18, 18)
                                .addGroup(jPAddProductWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPAddProductWindowLayout.createSequentialGroup()
                                        .addComponent(jBCancel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jBAddProduct))
                                    .addComponent(jTFNameProduct, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTFPrice)
                                    .addComponent(jTFProvider)
                                    .addComponent(jTFQuantity)
                                    .addComponent(jLImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jCBCategory, 0, 200, Short.MAX_VALUE))))))
                .addContainerGap())
        );
        jPAddProductWindowLayout.setVerticalGroup(
            jPAddProductWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPAddProductWindowLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLTittleAddProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPAddProductWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNameProduct)
                    .addComponent(jTFNameProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPAddProductWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLCategoryProduct)
                    .addComponent(jCBCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPAddProductWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLPrice)
                    .addComponent(jTFPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPAddProductWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLProvider)
                    .addComponent(jTFProvider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPAddProductWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLQuantity)
                    .addComponent(jTFQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPAddProductWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLImage)
                    .addComponent(jBAddImage))
                .addGap(18, 18, 18)
                .addComponent(jLImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPAddProductWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBCancel)
                    .addComponent(jBAddProduct))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPAddProductWindow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPAddProductWindow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelActionPerformed
        restoreFatherWindow();

        this.dispose();
    }//GEN-LAST:event_jBCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddProductWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddProductWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddProductWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddProductWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddProductWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAddImage;
    private javax.swing.JButton jBAddProduct;
    private javax.swing.JButton jBCancel;
    private javax.swing.JComboBox jCBCategory;
    private javax.swing.JLabel jLCategoryProduct;
    private javax.swing.JLabel jLImage;
    public static javax.swing.JLabel jLImagen;
    private javax.swing.JLabel jLNameProduct;
    private javax.swing.JLabel jLPrice;
    private javax.swing.JLabel jLProvider;
    private javax.swing.JLabel jLQuantity;
    private javax.swing.JLabel jLTittleAddProduct;
    private javax.swing.JPanel jPAddProductWindow;
    private javax.swing.JTextField jTFNameProduct;
    private javax.swing.JTextField jTFPrice;
    private javax.swing.JTextField jTFProvider;
    private javax.swing.JTextField jTFQuantity;
    // End of variables declaration//GEN-END:variables
}
