package view;

/**
 * @author LeonardoSotillo
 * @author FernandoRainier
 * version 1.0.0
 */
public class ConsultProduct extends VentaOnline {
    
    /**
     * Creates new form AddProductWindow
     */
    public ConsultProduct() {
        initComponents();
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBAddProduct = new javax.swing.JButton();
        jPAddProductWindow = new javax.swing.JPanel();
        jLTittleAddProduct = new javax.swing.JLabel();
        jLNameProduct = new javax.swing.JLabel();
        jLCategoryProduct = new javax.swing.JLabel();
        jLPrice = new javax.swing.JLabel();
        jLProvider = new javax.swing.JLabel();
        jLQuantityMin = new javax.swing.JLabel();
        jLImage = new javax.swing.JLabel();
        jTFNameProduct = new javax.swing.JTextField();
        jTFPrice = new javax.swing.JTextField();
        jTFProvider = new javax.swing.JTextField();
        jTFQuantityMin = new javax.swing.JTextField();
        jLImagen = new javax.swing.JLabel();
        jTFCategoryProduct = new javax.swing.JTextField();
        jTFImage = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTFDescription = new javax.swing.JTextField();
        jLQuantityMax = new javax.swing.JLabel();
        jTFQuantityMax = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jBAddProduct.setBackground(new java.awt.Color(255, 255, 255));
        jBAddProduct.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jBAddProduct.setText("AGREGAR");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPAddProductWindow.setBackground(new java.awt.Color(255, 255, 255));

        jLTittleAddProduct.setBackground(new java.awt.Color(255, 255, 255));
        jLTittleAddProduct.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLTittleAddProduct.setForeground(new java.awt.Color(0, 0, 255));
        jLTittleAddProduct.setText("CONSULTAR PRODUCTO");

        jLNameProduct.setBackground(new java.awt.Color(255, 255, 255));
        jLNameProduct.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLNameProduct.setText("Nombre");

        jLCategoryProduct.setBackground(new java.awt.Color(255, 255, 255));
        jLCategoryProduct.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLCategoryProduct.setText("Categoria");

        jLPrice.setBackground(new java.awt.Color(255, 255, 255));
        jLPrice.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLPrice.setText("Precio");

        jLProvider.setBackground(new java.awt.Color(255, 255, 255));
        jLProvider.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLProvider.setText("Proveedor de origen");

        jLQuantityMin.setBackground(new java.awt.Color(255, 255, 255));
        jLQuantityMin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLQuantityMin.setText("Cantidad minima en existencia");

        jLImage.setBackground(new java.awt.Color(255, 255, 255));
        jLImage.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLImage.setText("Imagen del producto");

        jTFNameProduct.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jTFPrice.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTFPrice.setToolTipText("");

        jTFProvider.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jTFQuantityMin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLImagen.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Descripcion");

        jLQuantityMax.setText("Cantidad existencia");

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPAddProductWindowLayout = new javax.swing.GroupLayout(jPAddProductWindow);
        jPAddProductWindow.setLayout(jPAddProductWindowLayout);
        jPAddProductWindowLayout.setHorizontalGroup(
            jPAddProductWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPAddProductWindowLayout.createSequentialGroup()
                .addGroup(jPAddProductWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPAddProductWindowLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLTittleAddProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPAddProductWindowLayout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jLNameProduct)
                        .addGap(18, 18, 18)
                        .addGroup(jPAddProductWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPAddProductWindowLayout.createSequentialGroup()
                                .addComponent(jLImagen, javax.swing.GroupLayout.DEFAULT_SIZE, 4, Short.MAX_VALUE)
                                .addGap(224, 224, 224))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPAddProductWindowLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jTFNameProduct))))
                    .addGroup(jPAddProductWindowLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPAddProductWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLQuantityMin)
                            .addComponent(jLProvider)
                            .addComponent(jLPrice)
                            .addComponent(jLCategoryProduct)
                            .addComponent(jLQuantityMax))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPAddProductWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTFProvider, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                            .addComponent(jTFCategoryProduct)
                            .addComponent(jTFPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                            .addComponent(jTFQuantityMin)
                            .addComponent(jTFQuantityMax)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPAddProductWindowLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPAddProductWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPAddProductWindowLayout.createSequentialGroup()
                                .addComponent(jLImage)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTFImage, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPAddProductWindowLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTFDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPAddProductWindowLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(28, 28, 28))
        );
        jPAddProductWindowLayout.setVerticalGroup(
            jPAddProductWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPAddProductWindowLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLTittleAddProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPAddProductWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNameProduct)
                    .addComponent(jTFNameProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPAddProductWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLProvider)
                    .addComponent(jTFProvider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPAddProductWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLQuantityMax)
                    .addComponent(jTFQuantityMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPAddProductWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLQuantityMin)
                    .addComponent(jTFQuantityMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPAddProductWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLPrice)
                    .addComponent(jTFPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPAddProductWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLCategoryProduct)
                    .addComponent(jTFCategoryProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPAddProductWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPAddProductWindowLayout.createSequentialGroup()
                        .addGroup(jPAddProductWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPAddProductWindowLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel1))
                            .addGroup(jPAddProductWindowLayout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jTFDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPAddProductWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLImage)
                            .addComponent(jTFImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPAddProductWindow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPAddProductWindow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

              

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAddProduct;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLCategoryProduct;
    private javax.swing.JLabel jLImage;
    public static javax.swing.JLabel jLImagen;
    private javax.swing.JLabel jLNameProduct;
    private javax.swing.JLabel jLPrice;
    private javax.swing.JLabel jLProvider;
    private javax.swing.JLabel jLQuantityMax;
    private javax.swing.JLabel jLQuantityMin;
    private javax.swing.JLabel jLTittleAddProduct;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPAddProductWindow;
    private javax.swing.JTextField jTFCategoryProduct;
    private javax.swing.JTextField jTFDescription;
    private javax.swing.JTextField jTFImage;
    private javax.swing.JTextField jTFNameProduct;
    private javax.swing.JTextField jTFPrice;
    private javax.swing.JTextField jTFProvider;
    private javax.swing.JTextField jTFQuantityMax;
    private javax.swing.JTextField jTFQuantityMin;
    // End of variables declaration//GEN-END:variables
}
